import { CodedError, OFFLINE_ERROR } from "./errors";
import type { Backend } from "./types";

/**
 * Used when the UI is loaded outside the Wails shell. It reports the absence
 * of a backend instead of inventing data (D021).
 */
export function createOfflineBackend(): Backend {
  const unavailable = () => Promise.reject(new CodedError({ code: OFFLINE_ERROR, params: {} }));
  return {
    connected: false,
    window: null,
    getAppInfo: unavailable,
    listRecentOperations: unavailable,
    getOperationEvents: unavailable,
    onOperationEvent: () => () => {},
    listAppSettings: unavailable,
    setAppSetting: unavailable,
    resetAppSetting: unavailable,
    logTail: unavailable,
    openLogFolder: unavailable,
    gamesView: unavailable,
    gameInstanceDetails: unavailable,
    workspace: unavailable,
    scanGames: unavailable,
    cancelOperation: unavailable,
    validateGameRoot: unavailable,
    suggestGameFolders: unavailable,
    verifyGameSetup: unavailable,
    manageGame: unavailable,
    setActiveInstance: unavailable,
    renameInstance: unavailable,
    hideInstance: unavailable,
    hideGame: unavailable,
    updateInstanceLocation: unavailable,
    unmanageGame: unavailable,
    openInstanceFolder: unavailable,
    pickFolder: unavailable,
    modList: unavailable,
    modDetails: unavailable,
    modFiles: unavailable,
    modHistory: unavailable,
    importQueue: unavailable,
    importFiles: unavailable,
    pickImportFiles: unavailable,
    pickImportFolder: unavailable,
    resolveImport: unavailable,
    cancelImport: unavailable,
    installMods: unavailable,
    reinstallMods: unavailable,
    previewModRemoval: unavailable,
    removeMods: unavailable,
    setModAttributes: unavailable,
    setModsCategory: unavailable,
    setModType: unavailable,
    setModsEnabled: unavailable,
    categories: unavailable,
    saveCategory: unavailable,
    deleteCategory: unavailable,
    openModFolder: unavailable,
    openModArchive: unavailable,
    profileList: unavailable,
    createProfile: unavailable,
    renameProfile: unavailable,
    setProfileNotes: unavailable,
    deleteProfile: unavailable,
    activateProfile: unavailable,
    compareProfiles: unavailable,
    transferSelection: unavailable,
    profileSnapshots: unavailable,
    createSnapshot: unavailable,
    restoreSnapshot: unavailable,
    modOrder: unavailable,
    moveMods: unavailable,
    createSeparator: unavailable,
    updateSeparator: unavailable,
    deleteSeparator: unavailable,
    setSeparatorBlockEnabled: unavailable,
    modRules: unavailable,
    previewOrderRule: unavailable,
    createOrderRule: unavailable,
    addDependencyRule: unavailable,
    addIncompatibilityRule: unavailable,
    removeRule: unavailable,
    setRuleDisabled: unavailable,
    orderHistory: unavailable,
    revertOrderChange: unavailable,
    undoOrderChange: unavailable,
    conflictPairs: unavailable,
    conflictPairDetail: unavailable,
    modConflicts: unavailable,
    modConflictFiles: unavailable,
    conflictIndicators: unavailable,
    ruleCycle: unavailable,
    setFileOverrides: unavailable,
    clearFileOverrides: unavailable,
    setFileExclusions: unavailable,
    markConflictsReviewed: unavailable,
    previewPairDecisions: unavailable,
    decidePairs: unavailable,
    onFileDrop: () => () => {},
  };
}
