import {
  PluginList as PluginListCall,
  PluginDetails as PluginDetailsCall,
  PluginRules as PluginRulesCall,
  LoadOrderView as LoadOrderViewCall,
  LoadOrderExplain as LoadOrderExplainCall,
  LoadOrderDiffApplied as LoadOrderDiffAppliedCall,
  SortPreview as SortPreviewCall,
  ExportLoadOrder as ExportLoadOrderCall,
  SetPluginsEnabled as SetPluginsEnabledCall,
  SortPlugins as SortPluginsCall,
  UndoLastSort as UndoLastSortCall,
  SetAutoSort as SetAutoSortCall,
  MovePlugins as MovePluginsCall,
  SetIndexLock as SetIndexLockCall,
  SetPluginGroup as SetPluginGroupCall,
  CreatePluginRule as CreatePluginRuleCall,
  RemovePluginRule as RemovePluginRuleCall,
  CreatePluginGroup as CreatePluginGroupCall,
  UpdatePluginGroup as UpdatePluginGroupCall,
  DeletePluginGroup as DeletePluginGroupCall,
  ApplyLoadOrder as ApplyLoadOrderCall,
  RestorePreviousLoadOrder as RestorePreviousLoadOrderCall,
  ImportLoadOrder as ImportLoadOrderCall,
  ResolveLoadOrderChange as ResolveLoadOrderChangeCall,
} from "../../wailsjs/go/bridge/App";
import {
  ActiveGameStatus as ActiveGameStatusCall,
  BackupStatus as BackupStatusCall,
  CancelRestore,
  CleanTempFiles,
  CreateBackup,
  DashboardLayout,
  Extensions as ExtensionsCall,
  FirstSteps as FirstStepsCall,
  InstanceOverview as InstanceOverviewCall,
  Launch,
  LaunchCheck as LaunchCheckCall,
  MoveArchiveStore,
  OpenBackupsFolder,
  OpenDataFolder,
  PickBackupFile,
  PreviewMoveArchives,
  RebuildPluginHeaderCache,
  RecentGames as RecentGamesCall,
  RestartApp,
  RestartState as RestartStateCall,
  RestoreBackup,
  RestoreBackupFromFile,
  Workarounds as WorkaroundsCall,
} from "../../wailsjs/go/bridge/App";
import {
  AttentionDiagnostics,
  Diagnostics as DiagnosticsCall,
  DismissNotifications,
  EnableImpact as EnableImpactCall,
  ExecuteDiagnosticAction,
  ExportSupportBundle,
  History as HistoryCall,
  MarkDiagnosticsVisited,
  MarkNotificationsRead,
  Notifications as NotificationsCall,
  ResetSuppressedDiagnostics,
  RevertHistoryEntry,
  RunHealthChecks,
  SendDesktopNotification,
  SuppressDiagnostic,
  Suppressions as SuppressionsCall,
  UnsuppressDiagnostic,
  CancelDeploy,
  CancelDeployDecision,
  ChangeDeployMethod,
  Deploy,
  DeployMethods,
  DeployStatus,
  ListInstanceSettings,
  MoveStaging,
  PendingDeployDecision,
  PreviewDeploy,
  PreviewMoveStaging,
  Purge,
  ReconcileDeploy,
  ResolveDeployDecision,
  ResolveExternalChanges,
  OpenLocationFolder,
  ScanExternalChanges,
  SetInstanceSetting,
  VerifyDeployment,
  ClearFileOverrides,
  ConflictIndicators,
  ConflictPairDetail,
  ConflictPairs,
  DecidePairs,
  MarkConflictsReviewed,
  ModConflictFiles,
  ModConflicts,
  PreviewPairDecisions,
  RuleCycle,
  SetFileExclusions,
  SetFileOverrides,
  ActivateProfile,
  AddDependencyRule,
  AddIncompatibilityRule,
  CompareProfiles,
  CreateOrderRule,
  CreateProfile,
  CreateSeparator,
  CreateSnapshot,
  DeleteProfile,
  DeleteSeparator,
  ModOrder,
  ModRules,
  MoveMods,
  OrderHistory,
  PreviewOrderRule,
  ProfileList,
  ProfileSnapshots,
  RemoveRule,
  RenameProfile,
  RestoreSnapshot,
  RevertOrderChange,
  SetProfileNotes,
  SetRuleDisabled,
  SetSeparatorBlockEnabled,
  TransferSelection,
  UndoOrderChange,
  UpdateSeparator,
  CancelImport,
  CancelOperation,
  Categories,
  DeleteCategory,
  ImportFiles,
  FomodImage,
  FomodState,
  ImportQueue,
  InstallMods,
  ModDetails,
  ModFiles,
  ModHistory,
  ModList,
  OpenModArchive,
  OpenModFolder,
  PickImportFiles,
  PickImportFolder,
  PreviewModRemoval,
  ReinstallMods,
  RemoveMods,
  ResolveImport,
  SaveCategory,
  SetModAttributes,
  SetModType,
  SetModsCategory,
  SetModsEnabled,
  GameInstanceDetails,
  GamesView,
  GetAppInfo,
  GetOperationEvents,
  HideGame,
  HideInstance,
  ListAppSettings,
  ListRecentOperations,
  LogTail,
  ManageGame,
  OpenInstanceFolder,
  OpenLogFolder,
  PickFolder,
  RenameInstance,
  ResetAppSetting,
  ScanGames,
  SetActiveInstance,
  SetAppSetting,
  SuggestGameFolders,
  UnmanageGame,
  UpdateInstanceLocation,
  ValidateGameRoot,
  VerifyGameSetup,
  Workspace,
} from "../../wailsjs/go/bridge/App";
import type { bridge } from "../../wailsjs/go/models";
import { EventsOn, OnFileDrop, OnFileDropOff, Quit, WindowMinimise, WindowToggleMaximise } from "../../wailsjs/runtime/runtime";
import type {
  ActiveGameStatus,
  ArchivesPreview,
  Backup,
  BackupStatus,
  Dashlet,
  Extension,
  FirstSteps,
  InstanceOverview,
  LaunchCheck,
  RecentGame,
  RestartState,
  TempCleanup,
  Workarounds,
  AppNotification,
  FomodView,
  DiagnosticActionResult,
  EnableImpact,
  HistoryEntry,
  Problems,
  Suppression,
  AppInfo,
  Backend,
  Category,
  ModDetails as ModDetailsT,
  ModFiles as ModFilesT,
  ModHistoryEntry,
  ModRow,
  QueueItem,
  RemovalPreview,
  GameFolders,
  GamesView as GamesViewT,
  LogEntry,
  ManagedGame,
  ManageResult,
  Operation,
  OperationEvent,
  RootCheck,
  Setting,
  SetupVerification,
  Workspace as WorkspaceT,
  ModOrder as ModOrderT,
  MoveResult,
  OrderChange,
  ProfileComparison,
  ProfileSummary,
  RestoreResult,
  Rule,
  RulePreview,
  Snapshot,
  ConflictIndicator,
  ConflictPairDetail as ConflictPairDetailT,
  ConflictPairs as ConflictPairsT,
  ModConflictFiles as ModConflictFilesT,
  ModConflicts as ModConflictsT,
  RuleCycle as RuleCycleT,
  DeployMethod as DeployMethodT,
  DeployPlan as DeployPlanT,
  DeployStatus as DeployStatusT,
  ExternalChanges as ExternalChangesT,
  StagingPreview as StagingPreviewT,
  LoadOrderDiff,
  LoadOrderView as LoadOrderViewT,
  PluginDetails as PluginDetailsT,
  PluginExplain,
  PluginList as PluginListT,
  PluginMoveResult,
  PluginRules as PluginRulesT,
  SortPreview as SortPreviewT,
  SortResult,
} from "./types";

/** Channel name emitted by internal/bridge (EventOperation). */
export const OPERATION_EVENT_CHANNEL = "operation:event";

export function isWailsRuntime(): boolean {
  const w = window as unknown as { go?: unknown; runtime?: unknown };
  return typeof w.go === "object" && typeof w.runtime === "object";
}

export function createWailsBackend(): Backend {
  return {
    connected: true,
    window: { minimise: WindowMinimise, toggleMaximise: WindowToggleMaximise, quit: Quit },
    getAppInfo: () => GetAppInfo() as Promise<AppInfo>,
    listRecentOperations: (limit) => ListRecentOperations(limit) as unknown as Promise<Operation[]>,
    getOperationEvents: (id) => GetOperationEvents(id) as unknown as Promise<OperationEvent[]>,
    onOperationEvent: (listener) =>
      EventsOn(OPERATION_EVENT_CHANNEL, (event: OperationEvent) => listener(event)),
    listAppSettings: () => ListAppSettings() as unknown as Promise<Setting[]>,
    setAppSetting: (key, value) => SetAppSetting(key, value),
    resetAppSetting: (key) => ResetAppSetting(key),
    logTail: (filter) => LogTail(filter as bridge.LogFilterDTO) as unknown as Promise<LogEntry[]>,
    openLogFolder: () => OpenLogFolder(),
    gamesView: (showHidden) => GamesView(showHidden) as unknown as Promise<GamesViewT>,
    gameInstanceDetails: (id) => GameInstanceDetails(id) as unknown as Promise<ManagedGame>,
    workspace: () => Workspace() as unknown as Promise<WorkspaceT>,
    scanGames: (mode) => ScanGames(mode),
    cancelOperation: (id) => CancelOperation(id),
    validateGameRoot: (gameId, root) => ValidateGameRoot(gameId, root) as unknown as Promise<RootCheck>,
    suggestGameFolders: (gameId, root, name) => SuggestGameFolders(gameId, root, name) as unknown as Promise<GameFolders>,
    verifyGameSetup: (setup) => VerifyGameSetup(setup as bridge.SetupDTO) as unknown as Promise<SetupVerification>,
    manageGame: (setup) => ManageGame(setup as bridge.SetupDTO) as unknown as Promise<ManageResult>,
    setActiveInstance: (id) => SetActiveInstance(id),
    renameInstance: (id, name) => RenameInstance(id, name),
    hideInstance: (id, hidden) => HideInstance(id, hidden),
    hideGame: (gameId, hidden) => HideGame(gameId, hidden),
    updateInstanceLocation: (id, root) => UpdateInstanceLocation(id, root),
    unmanageGame: (id, options) => UnmanageGame(id, options as bridge.UnmanageOptionsDTO),
    openInstanceFolder: (id, folder) => OpenInstanceFolder(id, folder),
    pickFolder: (title) => PickFolder(title),
    modList: (instance) => ModList(instance) as unknown as Promise<ModRow[]>,
    modDetails: (id) => ModDetails(id) as unknown as Promise<ModDetailsT>,
    modFiles: (id, filter, offset, limit) => ModFiles(id, filter, offset, limit) as unknown as Promise<ModFilesT>,
    modHistory: (id) => ModHistory(id) as unknown as Promise<ModHistoryEntry[]>,
    importQueue: (instance) => ImportQueue(instance) as unknown as Promise<QueueItem[]>,
    importFiles: (instance, paths) => ImportFiles(instance, paths),
    pickImportFiles: (instance, title) => PickImportFiles(instance, title),
    pickImportFolder: (instance, title) => PickImportFolder(instance, title),
    resolveImport: (operationId, answer) => ResolveImport(operationId, answer as bridge.AnswerDTO),
    fomodState: (operationId, selection) => FomodState(operationId, selection as bridge.FomodSelectionDTO[]) as unknown as Promise<FomodView>,
    fomodImage: (operationId, image) => FomodImage(operationId, image),
    cancelImport: (operationId) => CancelImport(operationId),
    installMods: (instance, ids) => InstallMods(instance, ids),
    reinstallMods: (instance, ids) => ReinstallMods(instance, ids),
    previewModRemoval: (instance, ids) => PreviewModRemoval(instance, ids) as unknown as Promise<RemovalPreview>,
    removeMods: (instance, ids, withArchives) => RemoveMods(instance, ids, withArchives),
    setModAttributes: (id, attributes) => SetModAttributes(id, attributes as bridge.ModAttributesDTO),
    setModsCategory: (instance, ids, category) => SetModsCategory(instance, ids, category),
    setModType: (id, modType) => SetModType(id, modType),
    setModsEnabled: (instance, ids, enabled) => SetModsEnabled(instance, ids, enabled),
    categories: (instance) => Categories(instance) as unknown as Promise<Category[]>,
    saveCategory: (instance, category) => SaveCategory(instance, category as bridge.CategoryDTO),
    deleteCategory: (instance, id) => DeleteCategory(instance, id),
    openModFolder: (id) => OpenModFolder(id),
    openModArchive: (id) => OpenModArchive(id),
    profileList: (instance) => ProfileList(instance) as unknown as Promise<ProfileSummary[]>,
    createProfile: (instance, name, from) => CreateProfile(instance, name, from),
    renameProfile: (id, name) => RenameProfile(id, name),
    setProfileNotes: (id, notes) => SetProfileNotes(id, notes),
    deleteProfile: (id) => DeleteProfile(id),
    activateProfile: (id) => ActivateProfile(id),
    compareProfiles: (a, b) => CompareProfiles(a, b) as unknown as Promise<ProfileComparison>,
    transferSelection: (from, to, options) => TransferSelection(from, to, options as bridge.TransferOptionsDTO),
    profileSnapshots: (id) => ProfileSnapshots(id) as unknown as Promise<Snapshot[]>,
    createSnapshot: (id) => CreateSnapshot(id),
    restoreSnapshot: (id, snapshot) => RestoreSnapshot(id, snapshot) as unknown as Promise<RestoreResult>,
    modOrder: (instance) => ModOrder(instance) as unknown as Promise<ModOrderT>,
    moveMods: (instance, request) => MoveMods(instance, request as bridge.MoveRequestDTO) as unknown as Promise<MoveResult>,
    createSeparator: (instance, label, color, anchor) => CreateSeparator(instance, label, color, anchor as bridge.AnchorDTO),
    updateSeparator: (instance, separator) => UpdateSeparator(instance, separator as bridge.SeparatorDTO),
    deleteSeparator: (instance, id) => DeleteSeparator(instance, id),
    setSeparatorBlockEnabled: (instance, id, enabled) => SetSeparatorBlockEnabled(instance, id, enabled),
    modRules: (instance) => ModRules(instance) as unknown as Promise<Rule[]>,
    previewOrderRule: (instance, winner, loser) => PreviewOrderRule(instance, winner, loser) as unknown as Promise<RulePreview>,
    createOrderRule: (instance, winner, loser) => CreateOrderRule(instance, winner, loser),
    addDependencyRule: (instance, mod, target, kind) => AddDependencyRule(instance, mod, target, kind),
    addIncompatibilityRule: (instance, a, b) => AddIncompatibilityRule(instance, a, b),
    removeRule: (instance, id) => RemoveRule(instance, id),
    setRuleDisabled: (instance, id, disabled) => SetRuleDisabled(instance, id, disabled),
    orderHistory: (instance) => OrderHistory(instance) as unknown as Promise<OrderChange[]>,
    revertOrderChange: (instance, id) => RevertOrderChange(instance, id),
    undoOrderChange: (instance) => UndoOrderChange(instance),
    conflictPairs: (instance, includeDisabled, search) => ConflictPairs(instance, includeDisabled, search) as unknown as Promise<ConflictPairsT>,
    conflictPairDetail: (instance, a, b, includeDisabled) => ConflictPairDetail(instance, a, b, includeDisabled) as unknown as Promise<ConflictPairDetailT>,
    modConflicts: (instance, mod) => ModConflicts(instance, mod) as unknown as Promise<ModConflictsT>,
    modConflictFiles: (instance, mod, filter, offset, limit) => ModConflictFiles(instance, mod, filter, offset, limit) as unknown as Promise<ModConflictFilesT>,
    conflictIndicators: (instance) => ConflictIndicators(instance) as unknown as Promise<ConflictIndicator[]>,
    ruleCycle: (instance) => RuleCycle(instance) as unknown as Promise<RuleCycleT | null>,
    setFileOverrides: (instance, winner, locations) => SetFileOverrides(instance, winner, locations),
    clearFileOverrides: (instance, locations) => ClearFileOverrides(instance, locations),
    setFileExclusions: (instance, mod, locations, hidden) => SetFileExclusions(instance, mod, locations, hidden),
    markConflictsReviewed: (instance, pairs) => MarkConflictsReviewed(instance, pairs),
    previewPairDecisions: (instance, decisions) => PreviewPairDecisions(instance, decisions) as unknown as Promise<RulePreview>,
    decidePairs: (instance, decisions) => DecidePairs(instance, decisions),
    deployStatus: (instance) => DeployStatus(instance) as unknown as Promise<DeployStatusT>,
    previewDeploy: (instance, purge) => PreviewDeploy(instance, purge) as unknown as Promise<DeployPlanT>,
    deploy: (instance) => Deploy(instance),
    purge: (instance) => Purge(instance),
    reconcileDeploy: (instance) => ReconcileDeploy(instance),
    cancelDeploy: (instance) => CancelDeploy(instance),
    pendingDeployDecision: (instance) => PendingDeployDecision(instance) as unknown as Promise<DeployPlanT | null>,
    resolveDeployDecision: (instance, operation, accept, decisions) =>
      ResolveDeployDecision(instance, operation, accept, decisions as unknown as bridge.ExternalDecisionDTO[]),
    cancelDeployDecision: (instance, operation) => CancelDeployDecision(instance, operation),
    verifyDeployment: (instance) => VerifyDeployment(instance) as unknown as Promise<ExternalChangesT>,
    scanExternalChanges: (instance) => ScanExternalChanges(instance),
    openLocationFolder: (instance, location) => OpenLocationFolder(instance, location),
    resolveExternalChanges: (instance, decisions) => ResolveExternalChanges(instance, decisions as unknown as bridge.ExternalDecisionDTO[]),
    deployMethods: async (instance) => ((await DeployMethods(instance)) ?? []) as unknown as DeployMethodT[],
    changeDeployMethod: (instance, method) => ChangeDeployMethod(instance, method),
    previewMoveStaging: (instance, path) => PreviewMoveStaging(instance, path) as unknown as Promise<StagingPreviewT>,
    moveStaging: (instance, path) => MoveStaging(instance, path),
    listInstanceSettings: async (instance) => ((await ListInstanceSettings(instance)) ?? []) as unknown as Setting[],
    setInstanceSetting: (instance, key, value) => SetInstanceSetting(instance, key, value),
    diagnostics: (instance) => DiagnosticsCall(instance) as unknown as Promise<Problems>,
    attentionDiagnostics: async () => ((await AttentionDiagnostics()) ?? []) as unknown as Problems[],
    markDiagnosticsVisited: (instance) => MarkDiagnosticsVisited(instance),
    runHealthChecks: (instance) => RunHealthChecks(instance),
    executeDiagnosticAction: (instance, key, actionId, index) =>
      ExecuteDiagnosticAction(instance, key, actionId, index) as unknown as Promise<DiagnosticActionResult>,
    suppressDiagnostic: (instance, key, wholeCode) => SuppressDiagnostic(instance, key, wholeCode),
    unsuppressDiagnostic: (key, code) => UnsuppressDiagnostic(key, code),
    suppressions: async () => ((await SuppressionsCall()) ?? []) as unknown as Suppression[],
    resetSuppressedDiagnostics: () => ResetSuppressedDiagnostics(),
    notifications: async (limit) => ((await NotificationsCall(limit)) ?? []) as unknown as AppNotification[],
    markNotificationsRead: (ids) => MarkNotificationsRead(ids),
    dismissNotifications: (ids) => DismissNotifications(ids),
    sendDesktopNotification: (id, title, body) => SendDesktopNotification(id, title, body),
    history: async (filter) => ((await HistoryCall(filter as bridge.HistoryFilterDTO)) ?? []) as unknown as HistoryEntry[],
    revertHistoryEntry: (id) => RevertHistoryEntry(id),
    exportSupportBundle: (title, defaultName) => ExportSupportBundle(title, defaultName),
    enableImpact: (instance, ids, enabling) => EnableImpactCall(instance, ids, enabling) as unknown as Promise<EnableImpact>,
    pluginList: (instance) => PluginListCall(instance) as unknown as Promise<PluginListT>,
    pluginDetails: (instance, name) => PluginDetailsCall(instance, name) as unknown as Promise<PluginDetailsT>,
    pluginRules: (instance) => PluginRulesCall(instance) as unknown as Promise<PluginRulesT>,
    loadOrderView: (instance) => LoadOrderViewCall(instance) as unknown as Promise<LoadOrderViewT>,
    loadOrderExplain: (instance, name) => LoadOrderExplainCall(instance, name) as unknown as Promise<PluginExplain>,
    loadOrderDiffApplied: (instance) => LoadOrderDiffAppliedCall(instance) as unknown as Promise<LoadOrderDiff>,
    sortPreview: (instance) => SortPreviewCall(instance) as unknown as Promise<SortPreviewT>,
    exportLoadOrder: (instance) => ExportLoadOrderCall(instance),
    setPluginsEnabled: (instance, plugins, enabled) => SetPluginsEnabledCall(instance, plugins, enabled),
    sortPlugins: (instance) => SortPluginsCall(instance) as unknown as Promise<SortResult>,
    undoLastSort: (instance) => UndoLastSortCall(instance),
    setAutoSort: (instance, on) => SetAutoSortCall(instance, on),
    movePlugins: (instance, plugins, index) => MovePluginsCall(instance, plugins, index) as unknown as Promise<PluginMoveResult>,
    setIndexLock: (instance, plugins, locked) => SetIndexLockCall(instance, plugins, locked),
    setPluginGroup: (instance, plugins, group) => SetPluginGroupCall(instance, plugins, group),
    createPluginRule: (instance, plugin, after) => CreatePluginRuleCall(instance, plugin, after),
    removePluginRule: (instance, id) => RemovePluginRuleCall(instance, id),
    createPluginGroup: (instance, name, after) => CreatePluginGroupCall(instance, name, after),
    updatePluginGroup: (instance, name, after) => UpdatePluginGroupCall(instance, name, after),
    deletePluginGroup: (instance, name) => DeletePluginGroupCall(instance, name),
    applyLoadOrder: (instance) => ApplyLoadOrderCall(instance),
    restorePreviousLoadOrder: (instance) => RestorePreviousLoadOrderCall(instance),
    importLoadOrder: (instance, text) => ImportLoadOrderCall(instance, text) as unknown as Promise<SortResult>,
    resolveLoadOrderChange: (instance, action) => ResolveLoadOrderChangeCall(instance, action),
    restartState: () => RestartStateCall() as unknown as Promise<RestartState>,
    restartApp: () => RestartApp(),
    openDataFolder: () => OpenDataFolder(),
    openBackupsFolder: () => OpenBackupsFolder(),
    backupStatus: () => BackupStatusCall() as unknown as Promise<BackupStatus>,
    createBackup: () => CreateBackup() as unknown as Promise<Backup>,
    restoreBackup: (id) => RestoreBackup(id),
    pickBackupFile: (title) => PickBackupFile(title),
    restoreBackupFromFile: (path) => RestoreBackupFromFile(path),
    cancelRestore: () => CancelRestore(),
    workarounds: () => WorkaroundsCall() as unknown as Promise<Workarounds>,
    cleanTempFiles: () => CleanTempFiles() as unknown as Promise<TempCleanup>,
    rebuildPluginHeaderCache: () => RebuildPluginHeaderCache(),
    previewMoveArchives: (instance, path) => PreviewMoveArchives(instance, path) as unknown as Promise<ArchivesPreview>,
    moveArchiveStore: (instance, path) => MoveArchiveStore(instance, path),
    extensions: async () => ((await ExtensionsCall()) ?? []) as unknown as Extension[],
    launchCheck: (instance) => LaunchCheckCall(instance) as unknown as Promise<LaunchCheck>,
    launch: (instance, request) => Launch(instance, request as bridge.LaunchRequestDTO),
    instanceOverview: (instance) => InstanceOverviewCall(instance) as unknown as Promise<InstanceOverview>,
    dashboardLayout: async () => ((await DashboardLayout()) ?? []) as unknown as Dashlet[],
    firstSteps: () => FirstStepsCall() as unknown as Promise<FirstSteps>,
    recentGames: async () => ((await RecentGamesCall()) ?? []) as unknown as RecentGame[],
    activeGameStatus: () => ActiveGameStatusCall() as unknown as Promise<ActiveGameStatus>,
    onFileDrop: (listener) => {
      // Only elements marked with --wails-drop-target receive drops
      // (main.go enables native file drop).
      OnFileDrop((_x, _y, paths) => listener(paths), true);
      return () => OnFileDropOff();
    },
  };
}
