// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function ActivateProfile(arg1:string):Promise<void>;

export function ActiveGameStatus():Promise<bridge.ActiveGameDTO>;

export function AddDependencyRule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AddIncompatibilityRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ApplyLoadOrder(arg1:string):Promise<string>;

export function AttentionDiagnostics():Promise<Array<bridge.ProblemsDTO>>;

export function BackupStatus():Promise<bridge.BackupStatusDTO>;

export function CancelDeploy(arg1:string):Promise<boolean>;

export function CancelDeployDecision(arg1:string,arg2:string):Promise<void>;

export function CancelImport(arg1:string):Promise<void>;

export function CancelOperation(arg1:string):Promise<boolean>;

export function CancelRestore():Promise<void>;

export function Categories(arg1:string):Promise<Array<bridge.CategoryDTO>>;

export function ChangeDeployMethod(arg1:string,arg2:string):Promise<string>;

export function CleanTempFiles():Promise<bridge.TempCleanupDTO>;

export function ClearFileOverrides(arg1:string,arg2:Array<bridge.LocationDTO>):Promise<void>;

export function CompareProfiles(arg1:string,arg2:string):Promise<bridge.ProfileComparisonDTO>;

export function ConflictIndicators(arg1:string):Promise<Array<bridge.ConflictIndicatorDTO>>;

export function ConflictPairDetail(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<bridge.ConflictPairDetailDTO>;

export function ConflictPairs(arg1:string,arg2:boolean,arg3:string):Promise<bridge.ConflictPairsDTO>;

export function CreateBackup():Promise<bridge.BackupDTO>;

export function CreateOrderRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreatePluginGroup(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreatePluginRule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSeparator(arg1:string,arg2:string,arg3:string,arg4:bridge.AnchorDTO):Promise<string>;

export function CreateSnapshot(arg1:string):Promise<string>;

export function DashboardLayout():Promise<Array<bridge.DashletDTO>>;

export function DecidePairs(arg1:string,arg2:Array<bridge.PairDecisionDTO>):Promise<void>;

export function DeleteCategory(arg1:string,arg2:string):Promise<void>;

export function DeletePluginGroup(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSeparator(arg1:string,arg2:string):Promise<void>;

export function Deploy(arg1:string):Promise<string>;

export function DeployMethods(arg1:string):Promise<Array<bridge.DeployMethodDTO>>;

export function DeployStatus(arg1:string):Promise<bridge.DeployStatusDTO>;

export function Diagnostics(arg1:string):Promise<bridge.ProblemsDTO>;

export function DismissNotifications(arg1:Array<string>):Promise<void>;

export function EnableImpact(arg1:string,arg2:Array<string>,arg3:boolean):Promise<bridge.EnableImpactDTO>;

export function ExecuteDiagnosticAction(arg1:string,arg2:string,arg3:string,arg4:number):Promise<bridge.DiagnosticActionResultDTO>;

export function ExportLoadOrder(arg1:string):Promise<string>;

export function ExportSupportBundle(arg1:string,arg2:string):Promise<string>;

export function Extensions():Promise<Array<bridge.ExtensionDTO>>;

export function FirstSteps():Promise<bridge.FirstStepsDTO>;

export function FomodImage(arg1:string,arg2:string):Promise<string>;

export function FomodState(arg1:string,arg2:Array<bridge.FomodSelectionDTO>):Promise<bridge.FomodViewDTO>;

export function GameInstanceDetails(arg1:string):Promise<bridge.ManagedGameDTO>;

export function GamesView(arg1:boolean):Promise<bridge.GamesViewDTO>;

export function GetAppInfo():Promise<bridge.AppInfo>;

export function GetOperationEvents(arg1:string):Promise<Array<bridge.EventDTO>>;

export function HideGame(arg1:string,arg2:boolean):Promise<void>;

export function HideInstance(arg1:string,arg2:boolean):Promise<void>;

export function History(arg1:bridge.HistoryFilterDTO):Promise<Array<bridge.HistoryEntryDTO>>;

export function ImportFiles(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ImportLoadOrder(arg1:string,arg2:string):Promise<bridge.SortResultDTO>;

export function ImportQueue(arg1:string):Promise<Array<bridge.QueueItemDTO>>;

export function InstallMods(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function InstanceOverview(arg1:string):Promise<bridge.InstanceOverviewDTO>;

export function Launch(arg1:string,arg2:bridge.LaunchRequestDTO):Promise<string>;

export function LaunchCheck(arg1:string):Promise<bridge.LaunchCheckDTO>;

export function ListAppSettings():Promise<Array<bridge.SettingDTO>>;

export function ListInstanceSettings(arg1:string):Promise<Array<bridge.SettingDTO>>;

export function ListRecentOperations(arg1:number):Promise<Array<bridge.OperationDTO>>;

export function LoadOrderDiffApplied(arg1:string):Promise<bridge.LoadOrderDiffDTO>;

export function LoadOrderExplain(arg1:string,arg2:string):Promise<bridge.PluginExplainDTO>;

export function LoadOrderView(arg1:string):Promise<bridge.LoadOrderViewDTO>;

export function LogTail(arg1:bridge.LogFilterDTO):Promise<Array<bridge.LogEntryDTO>>;

export function ManageGame(arg1:bridge.SetupDTO):Promise<bridge.ManageResultDTO>;

export function MarkConflictsReviewed(arg1:string,arg2:Array<bridge.PairRefDTO>):Promise<void>;

export function MarkDiagnosticsVisited(arg1:string):Promise<void>;

export function MarkNotificationsRead(arg1:Array<string>):Promise<void>;

export function ModConflictFiles(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<bridge.ModConflictFilesDTO>;

export function ModConflicts(arg1:string,arg2:string):Promise<bridge.ModConflictsDTO>;

export function ModDetails(arg1:string):Promise<bridge.ModDetailsDTO>;

export function ModFiles(arg1:string,arg2:string,arg3:number,arg4:number):Promise<bridge.ModFilesDTO>;

export function ModHistory(arg1:string):Promise<Array<bridge.ModHistoryDTO>>;

export function ModList(arg1:string):Promise<Array<bridge.ModRowDTO>>;

export function ModOrder(arg1:string):Promise<bridge.ModOrderDTO>;

export function ModRules(arg1:string):Promise<Array<bridge.RuleDTO>>;

export function MoveArchiveStore(arg1:string,arg2:string):Promise<string>;

export function MoveMods(arg1:string,arg2:bridge.MoveRequestDTO):Promise<bridge.MoveResultDTO>;

export function MovePlugins(arg1:string,arg2:Array<string>,arg3:number):Promise<bridge.PluginMoveResultDTO>;

export function MoveStaging(arg1:string,arg2:string):Promise<string>;

export function Notifications(arg1:number):Promise<Array<bridge.NotificationDTO>>;

export function OpenBackupsFolder():Promise<void>;

export function OpenDataFolder():Promise<void>;

export function OpenInstanceFolder(arg1:string,arg2:string):Promise<void>;

export function OpenLocationFolder(arg1:string,arg2:bridge.LocationDTO):Promise<void>;

export function OpenLogFolder():Promise<void>;

export function OpenModArchive(arg1:string):Promise<void>;

export function OpenModFolder(arg1:string):Promise<void>;

export function OrderHistory(arg1:string):Promise<Array<bridge.OrderChangeDTO>>;

export function PendingDeployDecision(arg1:string):Promise<bridge.DeployPlanDTO>;

export function PickBackupFile(arg1:string):Promise<string>;

export function PickFolder(arg1:string):Promise<string>;

export function PickImportFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function PickImportFolder(arg1:string,arg2:string):Promise<Array<string>>;

export function PluginDetails(arg1:string,arg2:string):Promise<bridge.PluginDetailsDTO>;

export function PluginList(arg1:string):Promise<bridge.PluginListDTO>;

export function PluginRules(arg1:string):Promise<bridge.PluginRulesDTO>;

export function PreviewDeploy(arg1:string,arg2:boolean):Promise<bridge.DeployPlanDTO>;

export function PreviewModRemoval(arg1:string,arg2:Array<string>):Promise<bridge.RemovalPreviewDTO>;

export function PreviewMoveArchives(arg1:string,arg2:string):Promise<bridge.ArchivesPreviewDTO>;

export function PreviewMoveStaging(arg1:string,arg2:string):Promise<bridge.StagingPreviewDTO>;

export function PreviewOrderRule(arg1:string,arg2:string,arg3:string):Promise<bridge.RulePreviewDTO>;

export function PreviewPairDecisions(arg1:string,arg2:Array<bridge.PairDecisionDTO>):Promise<bridge.RulePreviewDTO>;

export function ProfileList(arg1:string):Promise<Array<bridge.ProfileSummaryDTO>>;

export function ProfileSnapshots(arg1:string):Promise<Array<bridge.SnapshotDTO>>;

export function Purge(arg1:string):Promise<string>;

export function RebuildPluginHeaderCache():Promise<void>;

export function RecentGames():Promise<Array<bridge.RecentGameDTO>>;

export function ReconcileDeploy(arg1:string):Promise<string>;

export function ReinstallMods(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function RemoveMods(arg1:string,arg2:Array<string>,arg3:boolean):Promise<string>;

export function RemovePluginRule(arg1:string,arg2:string):Promise<void>;

export function RemoveRule(arg1:string,arg2:string):Promise<void>;

export function RenameInstance(arg1:string,arg2:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ResetAppSetting(arg1:string):Promise<void>;

export function ResetSuppressedDiagnostics():Promise<number>;

export function ResolveDeployDecision(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<bridge.ExternalDecisionDTO>):Promise<void>;

export function ResolveExternalChanges(arg1:string,arg2:Array<bridge.ExternalDecisionDTO>):Promise<string>;

export function ResolveImport(arg1:string,arg2:bridge.AnswerDTO):Promise<void>;

export function ResolveLoadOrderChange(arg1:string,arg2:string):Promise<string>;

export function RestartApp():Promise<void>;

export function RestartState():Promise<bridge.RestartStateDTO>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RestoreBackupFromFile(arg1:string):Promise<void>;

export function RestorePreviousLoadOrder(arg1:string):Promise<string>;

export function RestoreSnapshot(arg1:string,arg2:string):Promise<bridge.RestoreResultDTO>;

export function RevertHistoryEntry(arg1:string):Promise<void>;

export function RevertOrderChange(arg1:string,arg2:string):Promise<void>;

export function RuleCycle(arg1:string):Promise<bridge.RuleCycleDTO>;

export function RunHealthChecks(arg1:string):Promise<void>;

export function SaveCategory(arg1:string,arg2:bridge.CategoryDTO):Promise<string>;

export function ScanExternalChanges(arg1:string):Promise<void>;

export function ScanGames(arg1:string):Promise<string>;

export function SendDesktopNotification(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetActiveInstance(arg1:string):Promise<void>;

export function SetAppSetting(arg1:string,arg2:string):Promise<void>;

export function SetAutoSort(arg1:string,arg2:boolean):Promise<void>;

export function SetFileExclusions(arg1:string,arg2:string,arg3:Array<bridge.LocationDTO>,arg4:boolean):Promise<void>;

export function SetFileOverrides(arg1:string,arg2:string,arg3:Array<bridge.LocationDTO>):Promise<void>;

export function SetIndexLock(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SetInstanceSetting(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetModAttributes(arg1:string,arg2:bridge.ModAttributesDTO):Promise<void>;

export function SetModType(arg1:string,arg2:string):Promise<void>;

export function SetModsCategory(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function SetModsEnabled(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SetPluginGroup(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function SetPluginsEnabled(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SetProfileNotes(arg1:string,arg2:string):Promise<void>;

export function SetRuleDisabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetSeparatorBlockEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SortPlugins(arg1:string):Promise<bridge.SortResultDTO>;

export function SortPreview(arg1:string):Promise<bridge.SortPreviewDTO>;

export function SuggestGameFolders(arg1:string,arg2:string,arg3:string):Promise<bridge.FoldersDTO>;

export function SuppressDiagnostic(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Suppressions():Promise<Array<bridge.SuppressionDTO>>;

export function TransferSelection(arg1:string,arg2:string,arg3:bridge.TransferOptionsDTO):Promise<void>;

export function UndoLastSort(arg1:string):Promise<void>;

export function UndoOrderChange(arg1:string):Promise<void>;

export function UnmanageGame(arg1:string,arg2:bridge.UnmanageOptionsDTO):Promise<string>;

export function UnsuppressDiagnostic(arg1:string,arg2:string):Promise<void>;

export function UpdateInstanceLocation(arg1:string,arg2:string):Promise<void>;

export function UpdatePluginGroup(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function UpdateSeparator(arg1:string,arg2:bridge.SeparatorDTO):Promise<void>;

export function ValidateGameRoot(arg1:string,arg2:string):Promise<bridge.RootCheckDTO>;

export function VerifyDeployment(arg1:string):Promise<bridge.ExternalChangesDTO>;

export function VerifyGameSetup(arg1:bridge.SetupDTO):Promise<bridge.VerificationDTO>;

export function Workarounds():Promise<bridge.WorkaroundsDTO>;

export function Workspace():Promise<bridge.WorkspaceDTO>;
