// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelOperation(arg1) {
  return window['go']['bridge']['App']['CancelOperation'](arg1);
}

export function GameInstanceDetails(arg1) {
  return window['go']['bridge']['App']['GameInstanceDetails'](arg1);
}

export function GamesView(arg1) {
  return window['go']['bridge']['App']['GamesView'](arg1);
}

export function GetAppInfo() {
  return window['go']['bridge']['App']['GetAppInfo']();
}

export function GetOperationEvents(arg1) {
  return window['go']['bridge']['App']['GetOperationEvents'](arg1);
}

export function HideGame(arg1, arg2) {
  return window['go']['bridge']['App']['HideGame'](arg1, arg2);
}

export function HideInstance(arg1, arg2) {
  return window['go']['bridge']['App']['HideInstance'](arg1, arg2);
}

export function ListAppSettings() {
  return window['go']['bridge']['App']['ListAppSettings']();
}

export function ListRecentOperations(arg1) {
  return window['go']['bridge']['App']['ListRecentOperations'](arg1);
}

export function LogTail(arg1) {
  return window['go']['bridge']['App']['LogTail'](arg1);
}

export function ManageGame(arg1) {
  return window['go']['bridge']['App']['ManageGame'](arg1);
}

export function OpenInstanceFolder(arg1, arg2) {
  return window['go']['bridge']['App']['OpenInstanceFolder'](arg1, arg2);
}

export function OpenLogFolder() {
  return window['go']['bridge']['App']['OpenLogFolder']();
}

export function PickFolder(arg1) {
  return window['go']['bridge']['App']['PickFolder'](arg1);
}

export function RenameInstance(arg1, arg2) {
  return window['go']['bridge']['App']['RenameInstance'](arg1, arg2);
}

export function ResetAppSetting(arg1) {
  return window['go']['bridge']['App']['ResetAppSetting'](arg1);
}

export function ScanGames(arg1) {
  return window['go']['bridge']['App']['ScanGames'](arg1);
}

export function SetActiveInstance(arg1) {
  return window['go']['bridge']['App']['SetActiveInstance'](arg1);
}

export function SetAppSetting(arg1, arg2) {
  return window['go']['bridge']['App']['SetAppSetting'](arg1, arg2);
}

export function SuggestGameFolders(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SuggestGameFolders'](arg1, arg2, arg3);
}

export function UnmanageGame(arg1, arg2) {
  return window['go']['bridge']['App']['UnmanageGame'](arg1, arg2);
}

export function UpdateInstanceLocation(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateInstanceLocation'](arg1, arg2);
}

export function ValidateGameRoot(arg1, arg2) {
  return window['go']['bridge']['App']['ValidateGameRoot'](arg1, arg2);
}

export function VerifyGameSetup(arg1) {
  return window['go']['bridge']['App']['VerifyGameSetup'](arg1);
}

export function Workspace() {
  return window['go']['bridge']['App']['Workspace']();
}
