// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateProfile(arg1) {
  return window['go']['bridge']['App']['ActivateProfile'](arg1);
}

export function AddDependencyRule(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['AddDependencyRule'](arg1, arg2, arg3, arg4);
}

export function AddIncompatibilityRule(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['AddIncompatibilityRule'](arg1, arg2, arg3);
}

export function CancelDeploy(arg1) {
  return window['go']['bridge']['App']['CancelDeploy'](arg1);
}

export function CancelDeployDecision(arg1, arg2) {
  return window['go']['bridge']['App']['CancelDeployDecision'](arg1, arg2);
}

export function CancelImport(arg1) {
  return window['go']['bridge']['App']['CancelImport'](arg1);
}

export function CancelOperation(arg1) {
  return window['go']['bridge']['App']['CancelOperation'](arg1);
}

export function Categories(arg1) {
  return window['go']['bridge']['App']['Categories'](arg1);
}

export function ChangeDeployMethod(arg1, arg2) {
  return window['go']['bridge']['App']['ChangeDeployMethod'](arg1, arg2);
}

export function ClearFileOverrides(arg1, arg2) {
  return window['go']['bridge']['App']['ClearFileOverrides'](arg1, arg2);
}

export function CompareProfiles(arg1, arg2) {
  return window['go']['bridge']['App']['CompareProfiles'](arg1, arg2);
}

export function ConflictIndicators(arg1) {
  return window['go']['bridge']['App']['ConflictIndicators'](arg1);
}

export function ConflictPairDetail(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['ConflictPairDetail'](arg1, arg2, arg3, arg4);
}

export function ConflictPairs(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['ConflictPairs'](arg1, arg2, arg3);
}

export function CreateOrderRule(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['CreateOrderRule'](arg1, arg2, arg3);
}

export function CreateProfile(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['CreateProfile'](arg1, arg2, arg3);
}

export function CreateSeparator(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['CreateSeparator'](arg1, arg2, arg3, arg4);
}

export function CreateSnapshot(arg1) {
  return window['go']['bridge']['App']['CreateSnapshot'](arg1);
}

export function DecidePairs(arg1, arg2) {
  return window['go']['bridge']['App']['DecidePairs'](arg1, arg2);
}

export function DeleteCategory(arg1, arg2) {
  return window['go']['bridge']['App']['DeleteCategory'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['bridge']['App']['DeleteProfile'](arg1);
}

export function DeleteSeparator(arg1, arg2) {
  return window['go']['bridge']['App']['DeleteSeparator'](arg1, arg2);
}

export function Deploy(arg1) {
  return window['go']['bridge']['App']['Deploy'](arg1);
}

export function DeployMethods(arg1) {
  return window['go']['bridge']['App']['DeployMethods'](arg1);
}

export function DeployStatus(arg1) {
  return window['go']['bridge']['App']['DeployStatus'](arg1);
}

export function GameInstanceDetails(arg1) {
  return window['go']['bridge']['App']['GameInstanceDetails'](arg1);
}

export function GamesView(arg1) {
  return window['go']['bridge']['App']['GamesView'](arg1);
}

export function GetAppInfo() {
  return window['go']['bridge']['App']['GetAppInfo']();
}

export function GetOperationEvents(arg1) {
  return window['go']['bridge']['App']['GetOperationEvents'](arg1);
}

export function HideGame(arg1, arg2) {
  return window['go']['bridge']['App']['HideGame'](arg1, arg2);
}

export function HideInstance(arg1, arg2) {
  return window['go']['bridge']['App']['HideInstance'](arg1, arg2);
}

export function ImportFiles(arg1, arg2) {
  return window['go']['bridge']['App']['ImportFiles'](arg1, arg2);
}

export function ImportQueue(arg1) {
  return window['go']['bridge']['App']['ImportQueue'](arg1);
}

export function InstallMods(arg1, arg2) {
  return window['go']['bridge']['App']['InstallMods'](arg1, arg2);
}

export function ListAppSettings() {
  return window['go']['bridge']['App']['ListAppSettings']();
}

export function ListInstanceSettings(arg1) {
  return window['go']['bridge']['App']['ListInstanceSettings'](arg1);
}

export function ListRecentOperations(arg1) {
  return window['go']['bridge']['App']['ListRecentOperations'](arg1);
}

export function LogTail(arg1) {
  return window['go']['bridge']['App']['LogTail'](arg1);
}

export function ManageGame(arg1) {
  return window['go']['bridge']['App']['ManageGame'](arg1);
}

export function MarkConflictsReviewed(arg1, arg2) {
  return window['go']['bridge']['App']['MarkConflictsReviewed'](arg1, arg2);
}

export function ModConflictFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['App']['ModConflictFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function ModConflicts(arg1, arg2) {
  return window['go']['bridge']['App']['ModConflicts'](arg1, arg2);
}

export function ModDetails(arg1) {
  return window['go']['bridge']['App']['ModDetails'](arg1);
}

export function ModFiles(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['ModFiles'](arg1, arg2, arg3, arg4);
}

export function ModHistory(arg1) {
  return window['go']['bridge']['App']['ModHistory'](arg1);
}

export function ModList(arg1) {
  return window['go']['bridge']['App']['ModList'](arg1);
}

export function ModOrder(arg1) {
  return window['go']['bridge']['App']['ModOrder'](arg1);
}

export function ModRules(arg1) {
  return window['go']['bridge']['App']['ModRules'](arg1);
}

export function MoveMods(arg1, arg2) {
  return window['go']['bridge']['App']['MoveMods'](arg1, arg2);
}

export function MoveStaging(arg1, arg2) {
  return window['go']['bridge']['App']['MoveStaging'](arg1, arg2);
}

export function OpenInstanceFolder(arg1, arg2) {
  return window['go']['bridge']['App']['OpenInstanceFolder'](arg1, arg2);
}

export function OpenLogFolder() {
  return window['go']['bridge']['App']['OpenLogFolder']();
}

export function OpenModArchive(arg1) {
  return window['go']['bridge']['App']['OpenModArchive'](arg1);
}

export function OpenModFolder(arg1) {
  return window['go']['bridge']['App']['OpenModFolder'](arg1);
}

export function OrderHistory(arg1) {
  return window['go']['bridge']['App']['OrderHistory'](arg1);
}

export function PendingDeployDecision(arg1) {
  return window['go']['bridge']['App']['PendingDeployDecision'](arg1);
}

export function PickFolder(arg1) {
  return window['go']['bridge']['App']['PickFolder'](arg1);
}

export function PickImportFiles(arg1, arg2) {
  return window['go']['bridge']['App']['PickImportFiles'](arg1, arg2);
}

export function PickImportFolder(arg1, arg2) {
  return window['go']['bridge']['App']['PickImportFolder'](arg1, arg2);
}

export function PreviewDeploy(arg1, arg2) {
  return window['go']['bridge']['App']['PreviewDeploy'](arg1, arg2);
}

export function PreviewModRemoval(arg1, arg2) {
  return window['go']['bridge']['App']['PreviewModRemoval'](arg1, arg2);
}

export function PreviewMoveStaging(arg1, arg2) {
  return window['go']['bridge']['App']['PreviewMoveStaging'](arg1, arg2);
}

export function PreviewOrderRule(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['PreviewOrderRule'](arg1, arg2, arg3);
}

export function PreviewPairDecisions(arg1, arg2) {
  return window['go']['bridge']['App']['PreviewPairDecisions'](arg1, arg2);
}

export function ProfileList(arg1) {
  return window['go']['bridge']['App']['ProfileList'](arg1);
}

export function ProfileSnapshots(arg1) {
  return window['go']['bridge']['App']['ProfileSnapshots'](arg1);
}

export function Purge(arg1) {
  return window['go']['bridge']['App']['Purge'](arg1);
}

export function ReconcileDeploy(arg1) {
  return window['go']['bridge']['App']['ReconcileDeploy'](arg1);
}

export function ReinstallMods(arg1, arg2) {
  return window['go']['bridge']['App']['ReinstallMods'](arg1, arg2);
}

export function RemoveMods(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['RemoveMods'](arg1, arg2, arg3);
}

export function RemoveRule(arg1, arg2) {
  return window['go']['bridge']['App']['RemoveRule'](arg1, arg2);
}

export function RenameInstance(arg1, arg2) {
  return window['go']['bridge']['App']['RenameInstance'](arg1, arg2);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['bridge']['App']['RenameProfile'](arg1, arg2);
}

export function ResetAppSetting(arg1) {
  return window['go']['bridge']['App']['ResetAppSetting'](arg1);
}

export function ResolveDeployDecision(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['ResolveDeployDecision'](arg1, arg2, arg3);
}

export function ResolveImport(arg1, arg2) {
  return window['go']['bridge']['App']['ResolveImport'](arg1, arg2);
}

export function RestoreSnapshot(arg1, arg2) {
  return window['go']['bridge']['App']['RestoreSnapshot'](arg1, arg2);
}

export function RevertOrderChange(arg1, arg2) {
  return window['go']['bridge']['App']['RevertOrderChange'](arg1, arg2);
}

export function RuleCycle(arg1) {
  return window['go']['bridge']['App']['RuleCycle'](arg1);
}

export function SaveCategory(arg1, arg2) {
  return window['go']['bridge']['App']['SaveCategory'](arg1, arg2);
}

export function ScanGames(arg1) {
  return window['go']['bridge']['App']['ScanGames'](arg1);
}

export function SetActiveInstance(arg1) {
  return window['go']['bridge']['App']['SetActiveInstance'](arg1);
}

export function SetAppSetting(arg1, arg2) {
  return window['go']['bridge']['App']['SetAppSetting'](arg1, arg2);
}

export function SetFileExclusions(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['App']['SetFileExclusions'](arg1, arg2, arg3, arg4);
}

export function SetFileOverrides(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetFileOverrides'](arg1, arg2, arg3);
}

export function SetInstanceSetting(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetInstanceSetting'](arg1, arg2, arg3);
}

export function SetModAttributes(arg1, arg2) {
  return window['go']['bridge']['App']['SetModAttributes'](arg1, arg2);
}

export function SetModType(arg1, arg2) {
  return window['go']['bridge']['App']['SetModType'](arg1, arg2);
}

export function SetModsCategory(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetModsCategory'](arg1, arg2, arg3);
}

export function SetModsEnabled(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetModsEnabled'](arg1, arg2, arg3);
}

export function SetProfileNotes(arg1, arg2) {
  return window['go']['bridge']['App']['SetProfileNotes'](arg1, arg2);
}

export function SetRuleDisabled(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetRuleDisabled'](arg1, arg2, arg3);
}

export function SetSeparatorBlockEnabled(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SetSeparatorBlockEnabled'](arg1, arg2, arg3);
}

export function SuggestGameFolders(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['SuggestGameFolders'](arg1, arg2, arg3);
}

export function TransferSelection(arg1, arg2, arg3) {
  return window['go']['bridge']['App']['TransferSelection'](arg1, arg2, arg3);
}

export function UndoOrderChange(arg1) {
  return window['go']['bridge']['App']['UndoOrderChange'](arg1);
}

export function UnmanageGame(arg1, arg2) {
  return window['go']['bridge']['App']['UnmanageGame'](arg1, arg2);
}

export function UpdateInstanceLocation(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateInstanceLocation'](arg1, arg2);
}

export function UpdateSeparator(arg1, arg2) {
  return window['go']['bridge']['App']['UpdateSeparator'](arg1, arg2);
}

export function ValidateGameRoot(arg1, arg2) {
  return window['go']['bridge']['App']['ValidateGameRoot'](arg1, arg2);
}

export function VerifyDeployment(arg1) {
  return window['go']['bridge']['App']['VerifyDeployment'](arg1);
}

export function VerifyGameSetup(arg1) {
  return window['go']['bridge']['App']['VerifyGameSetup'](arg1);
}

export function Workspace() {
  return window['go']['bridge']['App']['Workspace']();
}
