// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function ActivateProfile(arg1:string):Promise<void>;

export function AddDependencyRule(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AddIncompatibilityRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CancelImport(arg1:string):Promise<void>;

export function CancelOperation(arg1:string):Promise<boolean>;

export function Categories(arg1:string):Promise<Array<bridge.CategoryDTO>>;

export function CompareProfiles(arg1:string,arg2:string):Promise<bridge.ProfileComparisonDTO>;

export function CreateOrderRule(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateSeparator(arg1:string,arg2:string,arg3:string,arg4:bridge.AnchorDTO):Promise<string>;

export function CreateSnapshot(arg1:string):Promise<string>;

export function DeleteCategory(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSeparator(arg1:string,arg2:string):Promise<void>;

export function GameInstanceDetails(arg1:string):Promise<bridge.ManagedGameDTO>;

export function GamesView(arg1:boolean):Promise<bridge.GamesViewDTO>;

export function GetAppInfo():Promise<bridge.AppInfo>;

export function GetOperationEvents(arg1:string):Promise<Array<bridge.EventDTO>>;

export function HideGame(arg1:string,arg2:boolean):Promise<void>;

export function HideInstance(arg1:string,arg2:boolean):Promise<void>;

export function ImportFiles(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ImportQueue(arg1:string):Promise<Array<bridge.QueueItemDTO>>;

export function InstallMods(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function ListAppSettings():Promise<Array<bridge.SettingDTO>>;

export function ListRecentOperations(arg1:number):Promise<Array<bridge.OperationDTO>>;

export function LogTail(arg1:bridge.LogFilterDTO):Promise<Array<bridge.LogEntryDTO>>;

export function ManageGame(arg1:bridge.SetupDTO):Promise<bridge.ManageResultDTO>;

export function ModDetails(arg1:string):Promise<bridge.ModDetailsDTO>;

export function ModFiles(arg1:string,arg2:string,arg3:number,arg4:number):Promise<bridge.ModFilesDTO>;

export function ModHistory(arg1:string):Promise<Array<bridge.ModHistoryDTO>>;

export function ModList(arg1:string):Promise<Array<bridge.ModRowDTO>>;

export function ModOrder(arg1:string):Promise<bridge.ModOrderDTO>;

export function ModRules(arg1:string):Promise<Array<bridge.RuleDTO>>;

export function MoveMods(arg1:string,arg2:bridge.MoveRequestDTO):Promise<bridge.MoveResultDTO>;

export function OpenInstanceFolder(arg1:string,arg2:string):Promise<void>;

export function OpenLogFolder():Promise<void>;

export function OpenModArchive(arg1:string):Promise<void>;

export function OpenModFolder(arg1:string):Promise<void>;

export function OrderHistory(arg1:string):Promise<Array<bridge.OrderChangeDTO>>;

export function PickFolder(arg1:string):Promise<string>;

export function PickImportFiles(arg1:string,arg2:string):Promise<Array<string>>;

export function PickImportFolder(arg1:string,arg2:string):Promise<Array<string>>;

export function PreviewModRemoval(arg1:string,arg2:Array<string>):Promise<bridge.RemovalPreviewDTO>;

export function PreviewOrderRule(arg1:string,arg2:string,arg3:string):Promise<bridge.RulePreviewDTO>;

export function ProfileList(arg1:string):Promise<Array<bridge.ProfileSummaryDTO>>;

export function ProfileSnapshots(arg1:string):Promise<Array<bridge.SnapshotDTO>>;

export function ReinstallMods(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function RemoveMods(arg1:string,arg2:Array<string>,arg3:boolean):Promise<string>;

export function RemoveRule(arg1:string,arg2:string):Promise<void>;

export function RenameInstance(arg1:string,arg2:string):Promise<void>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function ResetAppSetting(arg1:string):Promise<void>;

export function ResolveImport(arg1:string,arg2:bridge.AnswerDTO):Promise<void>;

export function RestoreSnapshot(arg1:string,arg2:string):Promise<bridge.RestoreResultDTO>;

export function RevertOrderChange(arg1:string,arg2:string):Promise<void>;

export function SaveCategory(arg1:string,arg2:bridge.CategoryDTO):Promise<string>;

export function ScanGames(arg1:string):Promise<string>;

export function SetActiveInstance(arg1:string):Promise<void>;

export function SetAppSetting(arg1:string,arg2:string):Promise<void>;

export function SetModAttributes(arg1:string,arg2:bridge.ModAttributesDTO):Promise<void>;

export function SetModType(arg1:string,arg2:string):Promise<void>;

export function SetModsCategory(arg1:string,arg2:Array<string>,arg3:string):Promise<void>;

export function SetModsEnabled(arg1:string,arg2:Array<string>,arg3:boolean):Promise<void>;

export function SetProfileNotes(arg1:string,arg2:string):Promise<void>;

export function SetRuleDisabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetSeparatorBlockEnabled(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SuggestGameFolders(arg1:string,arg2:string,arg3:string):Promise<bridge.FoldersDTO>;

export function TransferSelection(arg1:string,arg2:string,arg3:bridge.TransferOptionsDTO):Promise<void>;

export function UndoOrderChange(arg1:string):Promise<void>;

export function UnmanageGame(arg1:string,arg2:bridge.UnmanageOptionsDTO):Promise<string>;

export function UpdateInstanceLocation(arg1:string,arg2:string):Promise<void>;

export function UpdateSeparator(arg1:string,arg2:bridge.SeparatorDTO):Promise<void>;

export function ValidateGameRoot(arg1:string,arg2:string):Promise<bridge.RootCheckDTO>;

export function VerifyGameSetup(arg1:bridge.SetupDTO):Promise<bridge.VerificationDTO>;

export function Workspace():Promise<bridge.WorkspaceDTO>;
